{{ $fullName := include "Arr.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sonarr.name }}-{{ .Values.global.serviceAccount.nameSuffix }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Arr.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.sonarr.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ghostfolio.global.automount }}
