{{- if .Values.sonarr.enabled }}
{{ $noDownloadClaim := empty .Values.global.sharedVolumes.downloadTemp.existingClaim }}
{{ $noConfigClaim := empty .Values.sonarr.persistence.existingClaim }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sonarr.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Arr.labels" . | nindent 4 }}
  {{- with .Values.sonarr.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.sonarr.name }}
  serviceName: {{ .Values.sonarr.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.sonarr.name }}
    spec:
      terminationGracePeriodSeconds: 12
      securityContext: {}
      containers:
        - name: {{ .Values.sonarr.name }}
          image: {{ .Values.sonarr.image }}:{{ .Values.sonarr.tag }}
          imagePullPolicy: {{ .Values.sonarr.pullPolicy }}
          env:
            {{- if .Values.sonarr.env }}
            {{- toYaml .Values.sonarr.env | nindent 12 }}
            {{- end }}
            - name: TZ
              value: {{ default "Etc/UTC" .Values.global.timezone }}
            - name: PGID
              value: {{ .Values.global.groupId | quote }}
            - name: PUID
              value: {{ .Values.global.userId | quote }}
          ports:
            - containerPort: 8989
              name: {{ .Values.sonarr.name }}-web
          volumeMounts:
            - name: download-temp-volume
              mountPath: /dl
            - name: sonarr-config-volume
              mountPath: /config
            {{- $mountCounter := 0 }}
            {{- range .Values.global.sharedVolumes.tv }}
            {{- $mountCounter = add1 $mountCounter }}
            - name: media-volume-{{ $mountCounter }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- if .Values.sonarr.probes.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.sonarr.probes.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.sonarr.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.sonarr.probes.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.sonarr.resources }}
          resources:
            {{- toYaml .Values.sonarr.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- if $noDownloadClaim }}
        {{- if .Values.global.sharedVolumes.downloadTemp.customVolumDef }}
        {{- toYaml .Values.global.sharedVolumes.downloadTemp.customVolumDef | nindent 8 }}
        {{- else }}
        {{ fail "No download temp specification found" }}
        {{- end }}
        {{- else }}
        - name: download-temp-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.sharedVolumes.downloadTemp.existingClaim }}
        {{- end }}
        {{- if not $noConfigClaim }}
        - name: sonarr-config-volume
          persistentVolumeClaim:
            claimName: {{ .Values.sonarr.persistence.existingClaim }}
        {{- end }}
        {{- $volumeCounter := 0 }}
        {{- range .Values.global.sharedVolumes.tv }}
        {{- $volumeCounter = add1 $volumeCounter }}
        - name: media-volume-{{ $volumeCounter }}
          {{- if .existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
          {{- else }}
          {{- toYaml .customVolumeDef | nindent 10 }}
          {{- end }}
        {{- end }}
      {{- if .Values.sonarr.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml .Values.sonarr.nodeAffinity | nindent 10 }}
      {{- else if .Values.global.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml .Values.global.nodeAffinity | nindent 10 }}
      {{- end }}
      {{- if .Values.sonarr.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.sonarr.nodeSelector | nindent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.sonarr.tolerations }}
      tolerations:
        {{- toYaml .Values.sonarr.tolerations | nindent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    {{- if not $noConfigClaim }}
    []
    {{- end }}
    {{- if $noConfigClaim }}
    - metadata:
        name: sonarr-config-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.sonarr.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.sonarr.persistence.size }}
    {{- end }}
{{- end }}