{{- if .Values.global.ingress.enabled -}}
{{ $fullName := include "Arr.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Arr.labels" . | nindent 4 }}
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.global.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- if .Values.sabNZBD.enabled }}
    {{- range .Values.sabNZBD.ingressRoutes }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $.Values.sabNZBD.name }}
                port:
                  name: {{ $.Values.sabNZBD.name }}-web
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.sonarr.enabled }}
    {{- range .Values.sonarr.ingressRoutes }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $.Values.sonarr.name }}
                port:
                  name: {{ $.Values.sonarr.name }}-web
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.radarr.enabled }}
    {{- range .Values.radarr.ingressRoutes }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $.Values.radarr.name }}
                port:
                  name: {{ $.Values.radarr.name }}-web
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.overseerr.enabled }}
    {{- range .Values.overseerr.ingressRoutes }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | default "/" }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ $.Values.overseerr.name }}
                port:
                  name: {{ $.Values.overseerr.name }}-web
          {{- end }}
    {{- end }}
    {{- end }}
  tls:
    {{- if or .Values.global.autoTls.enabled .Values.global.ingress.tls }}
    {{- if .Values.sabNZBD.enabled }}
    {{- $counter := 0 }}
    {{- range .Values.sabNZBD.ingressRoutes }}
    {{- $counter = add1 $counter }}
    - hosts:
        - {{ .host | quote }}
      {{- if $.Values.global.autoTls.enabled }}
      secretName: {{ $.Values.sabNZBD.name }}-cert-secret-{{ $counter }}
      {{- else  }}
      secretName: {{ .tlsSecretName | default $.Values.global.ingress.tlsSecretName }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.sonarr.enabled }}
    {{- $counter := 0 }}
    {{- range .Values.sonarr.ingressRoutes }}
    {{- $counter = add1 $counter }}
    - hosts:
        - {{ .host | quote }}
      {{- if $.Values.global.autoTls.enabled }}
      secretName: {{ $.Values.sonarr.name }}-cert-secret-{{ $counter }}
      {{- else  }}
      secretName: {{ .tlsSecretName | default $.Values.global.ingress.tlsSecretName }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.radarr.enabled }}
    {{- $counter := 0 }}
    {{- range .Values.radarr.ingressRoutes }}
    {{- $counter = add1 $counter }}
    - hosts:
        - {{ .host | quote }}
      {{- if $.Values.global.autoTls.enabled }}
      secretName: {{ $.Values.radarr.name }}-cert-secret-{{ $counter }}
      {{- else  }}
      secretName: {{ .tlsSecretName | default $.Values.global.ingress.tlsSecretName }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.overseerr.enabled }}
    {{- $counter := 0 }}
    {{- range .Values.overseerr.ingressRoutes }}
    {{- $counter = add1 $counter }}
    - hosts:
        - {{ .host | quote }}
      {{- if $.Values.global.autoTls.enabled }}
      secretName: {{ $.Values.overseerr.name }}-cert-secret-{{ $counter }}
      {{- else  }}
      secretName: {{ .tlsSecretName | default $.Values.global.ingress.tlsSecretName }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- else }}
    []
    {{- end }}
{{- end }}