{{- if .Values.radarr.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.radarr.name }}-{{ .Values.global.serviceAccount.nameSuffix }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Arr.labels" . | nindent 4 }}
  annotations:
    internal.config.kubernetes.io/path: {{ .Template.Name }}
  {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.radarr.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.autoMountServiceToken }}
{{- end }}