{{- if and .Values.sabNZBD.enabled }}
{{- $counter := 0 -}}
{{- $name := .Values.sabNZBD.name -}}

{{- range .Values.sabNZBD.scripts }}
{{- $counter = add1 $counter }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-script-{{ .fileName | replace "." "-" }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "Arr.labels" $ | nindent 4 }}
data:
  {{ .fileName }}: |-
    {{- .script | nindent 4 }}
---
{{- end }}
{{- end }}