{{- if .Values.sabNZBD.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sabNZBD.name }}-{{ .Values.global.serviceAccount.nameSuffix }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Arr.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.sabNZBD.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.global.serviceAccount.autoMountServiceToken }}
{{- end }}