{{- if .Values.sabNZBD.enabled }}
{{- $name := .Values.sabNZBD.name -}}
{{ $noDownloadClaim := empty .Values.global.sharedVolumes.downloadTemp.existingClaim }}
{{ $noConfigClaim := empty .Values.sabNZBD.persistence.existingClaim }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "Arr.labels" . | nindent 4 }}
  {{- with .Values.sabNZBD.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  serviceName: {{ $name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      terminationGracePeriodSeconds: 12
      securityContext:
        runAsUser: {{ .Values.global.userId }}
        runAsGroup: {{ .Values.global.groupId }}
        fsGroup: {{ .Values.global.groupId }}
      containers:
        - name: {{ $name }}
          image: {{ .Values.sabNZBD.image }}:{{ .Values.sabNZBD.tag }}
          imagePullPolicy: {{ .Values.sabNZBD.pullPolicy }}
          env:
            {{- if .Values.sabNZBD.env }}
            {{- toYaml .Values.sabNZBD.env | nindent 12 }}
            {{- end }}
            - name: TZ
              value: {{ default "Etc/UTC" .Values.global.timezone }}
            - name: PGID
              value: {{ .Values.global.groupId | quote }}
            - name: PUID
              value: {{ .Values.global.userId | quote }}
          ports:
            - containerPort: 8080
              name: {{ $name }}-web
          volumeMounts:
            - name: download-temp-volume
              mountPath: /dl
            - name: sabnzbd-config-volume
              mountPath: /config
            {{- range .Values.sabNZBD.scripts }}
            - name: script-{{ .fileName | replace "." "-" }}-volume
              subPath: {{ .fileName }}
              mountPath: /scripts/{{ .fileName }}
            {{- end }}
          {{- if .Values.sabNZBD.probes.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.sabNZBD.probes.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.sabNZBD.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.sabNZBD.probes.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.sabNZBD.resources }}
          resources:
            {{- toYaml .Values.sabNZBD.resources | nindent 12 }}
          {{- end }}
      volumes:
        {{- if $noDownloadClaim }}
        {{- if .Values.global.sharedVolumes.downloadTemp.customVolumDef }}
        {{- toYaml .Values.global.sharedVolumes.downloadTemp.customVolumDef | nindent 8 }}
        {{- else }}
        {{ fail "No download temp specification found" }}
        {{- end }}
        {{- else }}
        - name: download-temp-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.sharedVolumes.downloadTemp.existingClaim }}
        {{- end }}
        {{ if not $noConfigClaim }}
        - name: sabnzbd-config-volume
          persistentVolumeClaim:
            claimName: {{ .Values.sabNZBD.persistence.existingClaim }}
        {{- end }}
        {{- range .Values.sabNZBD.scripts }}
        - name: script-{{ .fileName | replace "." "-" }}-volume
          configMap:
            name: {{ $name }}-script-{{ .fileName | replace "." "-" }}
            defaultMode: 0550
        {{- end }}
      {{- if .Values.sabNZBD.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml .Values.sabNZBD.nodeAffinity | nindent 10 }}
      {{- else if .Values.global.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml .Values.global.nodeAffinity | nindent 10 }}
      {{- end }}
      {{- if .Values.sabNZBD.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.sabNZBD.nodeSelector | nindent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.sabNZBD.tolerations }}
      tolerations:
        {{- toYaml .Values.sabNZBD.tolerations | nindent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    {{- if not $noConfigClaim }}
    []
    {{- end }}
    {{- if $noConfigClaim }}
    - metadata:
        name: sabnzbd-config-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.sabNZBD.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.sabNZBD.persistence.size }}
    {{- end }}
{{- end }}